// <auto-generated />
namespace ConstructEComm.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addfullnamemobilenumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfullnamemobilenumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201803101237303_add-fullname-mobilenumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
